########################################################
### 开发环境配置
########################################################
# springboot配置
spring:
    # 多环境配置
    profiles: dev
    # dubbo
    dubbo:
        application:
            name: sefarm-web
        registry:
            address: zookeeper://127.0.0.1:2181
            timeout: 40000
        scan: com.sefarm
    # srping mvc
    mvc:
        static-path-pattern: /static/**
        view:
            prefix: /WEB-INF/view
#            suffix: .html


########################################################
### server 配置
########################################################
server:
    port: 80
    context-path: /
#    tomcat:
#        uri-encoding: utf-8

###################  sefarm配置  ###################
sefarm:
    swagger-open: false #是否开启swagger (true/false)
    kaptcha-open: false #是否开启登录时验证码 (true/false)
    session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
    file-upload-path: D:\imageTemple  #文件上传目录(不配置的话为java.io.tmpdir目录)
    muti-datasource-open: false #是否开启多数据源(true/false)
    spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
    session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
    session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  beetl配置  ###################
beetl:
    delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
    delimiter-statement-end: null
    resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
    resource-tagsuffix: tag
    resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

